<a href="https://colab.research.google.com/github/AKSHAYAVISWA/HexaTraining/blob/main/Weekly_Capstone_Projects/Customer_Order_Insights/Week3_Orders_Analytics_Pyspark.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
!pip install pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.12/dist-packages (4.0.3)
Requirement already satisfied: py4j<0.10.9.10,>=0.10.9.7 in /usr/local/lib/python3.12/dist-packages (from pyspark) (0.10.9.9)

In [21]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, datediff, when, count

spark = SparkSession.builder \
    .appName("Week3_Order_Analysis") \
    .getOrCreate()

print("Spark Started Successfully!")

Spark Started Successfully!

In [22]:
import pandas as pd

orders = pd.DataFrame({
    "order_id":[101,102,103,104,105,106,107,108],
    "customer_id":[1,2,3,4,5,2,1,3],
    "order_date":[
        "2024-01-01",
        "2024-01-02",
        "2024-01-03",
        "2024-01-04",
        "2024-01-05",
        "2024-01-06",
        "2024-01-07",
        "2024-01-08"
    ],
    "delivery_date":[
        "2024-01-05",
        "2024-01-10",
        "2024-01-04",
        "2024-01-12",
        "2024-01-07",
        "2024-01-15",
        "2024-01-08",
        "2024-01-18"
    ]
})

orders.to_csv("orders.csv", index=False)

print("orders.csv created")
orders

orders.csv created

   order_id  customer_id  order_date delivery_date
0       101            1  2024-01-01    2024-01-05
1       102            2  2024-01-02    2024-01-10
2       103            3  2024-01-03    2024-01-04
3       104            4  2024-01-04    2024-01-12
4       105            5  2024-01-05    2024-01-07
5       106            2  2024-01-06    2024-01-15
6       107            1  2024-01-07    2024-01-08
7       108            3  2024-01-08    2024-01-18

In [23]:
customers = pd.DataFrame({
    "customer_id":[1,2,3,4,5],
    "customer_name":[
        "Akshaya",
        "Rahul",
        "Priya",
        "Arun",
        "Sneha"
    ],
    "region":[
        "South",
        "North",
        "East",
        "West",
        "South"
    ]
})

customers.to_csv("customers.csv", index=False)

print("customers.csv created")
customers

customers.csv created

   customer_id customer_name region
0            1       Akshaya  South
1            2         Rahul  North
2            3         Priya   East
3            4          Arun   West
4            5         Sneha  South

In [24]:
orders_df = spark.read.csv(
    "orders.csv",
    header=True,
    inferSchema=True
)

customers_df = spark.read.csv(
    "customers.csv",
    header=True,
    inferSchema=True
)

print("Orders Table")
orders_df.show()

print("Customers Table")
customers_df.show()

Orders Table
+--------+-----------+----------+-------------+
|order_id|customer_id|order_date|delivery_date|
+--------+-----------+----------+-------------+
|     101|          1|2024-01-01|   2024-01-05|
|     102|          2|2024-01-02|   2024-01-10|
|     103|          3|2024-01-03|   2024-01-04|
|     104|          4|2024-01-04|   2024-01-12|
|     105|          5|2024-01-05|   2024-01-07|
|     106|          2|2024-01-06|   2024-01-15|
|     107|          1|2024-01-07|   2024-01-08|
|     108|          3|2024-01-08|   2024-01-18|
+--------+-----------+----------+-------------+

Customers Table
+-----------+-------------+------+
|customer_id|customer_name|region|
+-----------+-------------+------+
|          1|      Akshaya| South|
|          2|        Rahul| North|
|          3|        Priya|  East|
|          4|         Arun|  West|
|          5|        Sneha| South|
+-----------+-------------+------+

In [25]:
joined_df = orders_df.join(
    customers_df,
    on="customer_id",
    how="inner"
)

print("Joined Table")
joined_df.show()

Joined Table
+-----------+--------+----------+-------------+-------------+------+
|customer_id|order_id|order_date|delivery_date|customer_name|region|
+-----------+--------+----------+-------------+-------------+------+
|          1|     101|2024-01-01|   2024-01-05|      Akshaya| South|
|          2|     102|2024-01-02|   2024-01-10|        Rahul| North|
|          3|     103|2024-01-03|   2024-01-04|        Priya|  East|
|          4|     104|2024-01-04|   2024-01-12|         Arun|  West|
|          5|     105|2024-01-05|   2024-01-07|        Sneha| South|
|          2|     106|2024-01-06|   2024-01-15|        Rahul| North|
|          1|     107|2024-01-07|   2024-01-08|      Akshaya| South|
|          3|     108|2024-01-08|   2024-01-18|        Priya|  East|
+-----------+--------+----------+-------------+-------------+------+

In [18]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("Week3").getOrCreate()

orders = spark.createDataFrame(orders)
customers = spark.createDataFrame(customers)

In [19]:

joined = orders.join(customers, on="customer_id", how="inner")

joined.show()

+-----------+--------+----------+-------------+-------------+------+
|customer_id|order_id|order_date|delivery_date|customer_name|region|
+-----------+--------+----------+-------------+-------------+------+
|          1|     101|2024-01-01|   2024-01-05|      Akshaya| South|
|          1|     107|2024-01-07|   2024-01-08|      Akshaya| South|
|          2|     102|2024-01-02|   2024-01-10|        Rahul| North|
|          2|     106|2024-01-06|   2024-01-15|        Rahul| North|
|          3|     103|2024-01-03|   2024-01-04|        Priya|  East|
|          3|     108|2024-01-08|   2024-01-18|        Priya|  East|
|          4|     104|2024-01-04|   2024-01-12|         Arun|  West|
|          5|     105|2024-01-05|   2024-01-07|        Sneha| South|
+-----------+--------+----------+-------------+-------------+------+

In [26]:
joined_df = joined_df.withColumn(
    "delivery_days",
    datediff(col("delivery_date"), col("order_date"))
)

joined_df = joined_df.withColumn(
    "Delayed",
    when(col("delivery_days") > 5, "Yes").otherwise("No")
)

print("Orders with Delay Status")
joined_df.show()

Orders with Delay Status
+-----------+--------+----------+-------------+-------------+------+-------------+-------+
|customer_id|order_id|order_date|delivery_date|customer_name|region|delivery_days|Delayed|
+-----------+--------+----------+-------------+-------------+------+-------------+-------+
|          1|     101|2024-01-01|   2024-01-05|      Akshaya| South|            4|     No|
|          2|     102|2024-01-02|   2024-01-10|        Rahul| North|            8|    Yes|
|          3|     103|2024-01-03|   2024-01-04|        Priya|  East|            1|     No|
|          4|     104|2024-01-04|   2024-01-12|         Arun|  West|            8|    Yes|
|          5|     105|2024-01-05|   2024-01-07|        Sneha| South|            2|     No|
|          2|     106|2024-01-06|   2024-01-15|        Rahul| North|            9|    Yes|
|          1|     107|2024-01-07|   2024-01-08|      Akshaya| South|            1|     No|
|          3|     108|2024-01-08|   2024-01-18|        Priya|  East|           10|    Yes|
+-----------+--------+----------+-------------+-------------+------+-------------+-------+

In [27]:
result = joined_df.filter(col("Delayed")=="Yes") \
                  .groupBy("region") \
                  .agg(count("*").alias("Delayed_Orders"))

print("Delayed Orders by Region")
result.show()

Delayed Orders by Region
+------+--------------+
|region|Delayed_Orders|
+------+--------------+
|  East|             1|
|  West|             1|
| North|             2|
+------+--------------+

In [28]:
result.coalesce(1).write \
      .mode("overwrite") \
      .option("header", True) \
      .csv("output")

print("Output saved successfully!")

Output saved successfully!

In [29]:
import os

print(os.listdir("output"))

['part-00000-3dbef884-9683-4e56-9cbb-e0e285394b7a-c000.csv', '.part-00000-3dbef884-9683-4e56-9cbb-e0e285394b7a-c000.csv.crc', '._SUCCESS.crc', '_SUCCESS']